# Generated by Django 6.0 on 2025-12-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.TextField(default='main', max_length=20),
        ),
    ]
