# Generated by Django 6.0 on 2025-12-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_config_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
