# Generated by Django 6.0 on 2025-12-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_telegramusers_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
