# Generated by Django 6.0 on 2025-12-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_telegramusers_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
